### ISSUE TITLE
为啥你npm上发布的 只有一个中文校验

### ISSUE THREAD

**Issue by zhayes** [yinxin630/useful-regex#1]
npm 上 install 的内容只有一个？

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global['useful-regex'] = factory());
}(this, (function () { 'use strict';

var index = {
    // 中文字符
    Chinese: /[\u4e00-\u9fa5]/,
};

return index;

})));

**Comment by zhayes** [comment]
又看到个 bjh-regex ，麻烦 更正下好不。文档有点误导

**Comment by zhayes** [comment]
已经有19开头的手机号了

**Comment by zhayes** [comment]
望及时更新

**Comment by yinxin630** [comment]
抱歉, 感谢您的反馈. 目前已经更新版本号到0.0.4, 新增198/199号码, 包内容只有Chinese的问题也修复了
